# Generated by Django 3.2.16 on 2024-08-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_project_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
