# Generated by Django 3.2.16 on 2024-08-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20240805_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('project', 'task')},
        ),
    ]
