# Generated by Django 3.2.16 on 2024-08-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_todo_sequential_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='sequential_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('project', 'task', 'sequential_number')},
        ),
    ]
