# Generated by Django 3.2.16 on 2024-08-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20240805_1939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('project', 'task')},
        ),
    ]
